version: '3'


vars:
  MAIN_TASKFILE_PATH: "../../Taskfile.yml"

tasks:
  
  labels-sync: 
    desc: Sync your repo labels with labels reference
    summary: |
      SYNOPSIS: 
        Sync your repo labels with labels reference

      SYNTAX
        task {{ .TASK }} GITHUB_TOKEN=<VALUE>

      PARAMETERS
        GITHUB_TOKEN: GitHub API Access Token   

      EXAMPLES:
        Example 1:
          $ task {{ .TASK }} GITHUB_TOKEN=xxxx-zzz-cccc

        Example 2:
          $ task {{ .TASK }} GITHUB_TOKEN=xxxx-zzz-cccc
    dir: adhocs/github
    env:
      GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
      TASK_NAME: "{{ .TASK }}"
      MAIN_TASKFILE_PATH: "{{ .MAIN_TASKFILE_PATH }}"
    cmds:
      - ./scripts/labels-sync.sh
      